version: "3.9"

services:
  db:
    image: postgres:15
    container_name: earthquake_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: earthquakes
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  rust:
    image: rust:1.90
    container_name: earthquake_rust
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: >
      sh -c "
        cargo install sqlx-cli --no-default-features --features postgres,rustls &&
        sqlx migrate run &&
        cargo run --release
      "
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/earthquakes
    depends_on:
      - db
    ports:
      - "42069:42069"

volumes:
  db_data:
